version: '3'

services:
###> doctrine/doctrine-bundle ###
  database:
    container_name: postgres
    image: postgres:13.3-alpine
    environment:
     # POSTGRES_DB: ${POSTGRES_DB:-app}
      # You should definitely change the password in production
      POSTGRES_PASSWORD: 12345
      POSTGRES_USER: postgres
    ports:
      - "5432:5432"
